### ISSUE TITLE
The last image in image sets not grabbed anymore

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#1]
Title. [Example post here.](https://www.instagram.com/p/CD17utOJ_yg/) Two-image sets are also affected (i.e. only the first image can be grabbed). Videos are unaffected.

**Comment by saschaheim** [comment]
Ok will Check that tomorrow.
Thanks 🙏

**Comment by saschaheim** [comment]
Have checked it and i cannot reproduce your issue.
Are you sure you have the latest version 4.
What browser did you use?

**Comment by Orudeon** [comment]
Firefox 79.0, United States, using version 4.0.0. Windows 10 64-bit, if that also matters.

**Comment by saschaheim** [comment]
Thanks, will look into it.

**Comment by saschaheim** [comment]
I have reproduced your issue in Firefox and will research a solution.
Will test more browsers on your issue for an proper fix.

**Comment by saschaheim** [comment]
New version released. 
It should really work again now.
