### ISSUE TITLE
Timeline image carousel behaving weird with skipping to videos/images being skipped (8.0.2)

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#10]
Hello! This seems like a complicated issue.

[Here's a photo/video post](https://www.instagram.com/p/CPfk5kKJB-9/) where images are being skipped over in favor of trying to download a video.

[Here's a photo/video post](https://www.instagram.com/p/CPjhcxihGD9/) where it grabs the first photo a second time instead of the second photo, then it properly grabs videos.

**Comment by saschaheim** [comment]
Is it a modal post or a direct post?

**Comment by saschaheim** [comment]
You see a modal that shows "Trying to load" and nothing happens?
I can reproduce this and will try to re-develope the video downloader some videos are using new technology that instagram introduced in may 21.

Sorry for the inconvenience...

**Comment by Orudeon** [comment]
I actually didn't notice that videos were sometimes failing to download, as you pointed out.  I had only noticed that images were being skipped. So yes, something is also going wrong with video downloading I suppose.

**Comment by saschaheim** [comment]
I could not reproduce your problem with skipped images.
Everything works for me, even with newly installed browsers.

Need more infos about installed OS and browser with version number.

PS: Please try the new version 8.1.0 and write me if the bug is gone
Thanks
