### ISSUE TITLE
Can't seem to bookmark it of Firefox.

### ISSUE THREAD

**Issue by MaestroDaVinci** [saschaheim/instantgram#11]
So on today i was notified that there is an update to this one and i went to the website and tried to drag it up to the bookmark bar, however for some reason this version can't be bookmarked on Firefox. I'm on Firefox 89.0.1 (64-bit) and i tried it both with addons and without, and in both cases i can't drag it up to the bookmark bar or even click with right click and click on bookmark, but nothing works. On chrome it works as intended i can just drag it to the bookmark bar, but on Firefox it doesn't work. I tried on a similar project and there it works.

**Comment by saschaheim** [comment]
Hello,
thanks Firefox is on version 9 currently not supported. As the changelog says.

v9.0.0 - [instangram] Now you can download a whole user profile.
But with limits it only works in Chrome, Opera, Safari. Firefox currently are not supported.

**Comment by MaestroDaVinci** [comment]
So i can't use that one firefox anymore or is it just this version. And if so where can i add a previous version?

**Comment by saschaheim** [comment]
I will do researching on support firefox.
Yes compability page is here ->
https://thinkbig-company.github.io/instantgram/v8.1.1/

**Comment by saschaheim** [comment]
Firefox should be supported again in version 10.0.0
Thanks for using ^_^

**Comment by MaestroDaVinci** [comment]
Yep it works now.
