### ISSUE TITLE
"this.modal is null" error when attempting to download a video with v10.0.3

### ISSUE THREAD

**Issue by ale-carra** [saschaheim/instantgram#12]
When I try to download a feed video with v10.0.3 the modal flashes but the video does not download. Instead I get the following error

Uncaught (in promise) TypeError: this.modal is null
(function(){;(()=>{"use strict";function l(t){return new Promise(function(e){setTimeout(e,t)})}class i{constructor(e){this.modal=null,this.imageURL=e:1:5896

This happens on one of my accounts, on the other account it works fine. I am using Firefox 90

**Comment by saschaheim** [comment]
You have already created an issue in the past with the same problem.
I would love to help you but I have no idea how.
I'll try to create a version for you where I can debug a lot of things so maybe I can fix the problem.

**Comment by saschaheim** [comment]
Hello,

i cannot replicate this issue on any browser version.

Will research again if the issue appears again.

Thanks Sascha
