### ISSUE TITLE
Reels not working in 10.0.3

### ISSUE THREAD

**Issue by hchorey** [saschaheim/instantgram#13]
When loading reels in 10.0.3, I'm getting a blank video box.  However, I noticed this:

Non-working link generated by 10.0.3 begins with `scontent.fric1-1.fna.fbcdn.net`

I can get the URL to work and load correctly if I change the beginning of the URL to `scontent.cdninstagram.com`

Hope that helps!

**Comment by saschaheim** [comment]
I need an example url.
Can you share some?

Thanks

**Comment by hchorey** [comment]
https://www.instagram.com/reel/CSfJxzCjzwE/

**Comment by saschaheim** [comment]
Hmm it shows me a correct working url
[test](https://scontent.cdninstagram.com/v/t50.2886-16/237277898_356701145942621_5572971298026958959_n.mp4?_nc_ht=scontent-ham3-1.cdninstagram.com&_nc_cat=105&_nc_ohc=5vtoVq3n3d0AX-ju2YN&edm=APfKNqwBAAAA&ccb=7-4&oe=6128BBA6&oh=3bd7bb02415b9d3899d6e0155f32879e&_nc_sid=74f7ba)

**Comment by hchorey** [comment]
I agree, that test link you just posted works for me.  However, when I click the 10.0.3 bookmarklet, it tries to load this:

[my-test](https://scontent.fric1-2.fna.fbcdn.net/v/t50.2886-16/237277898_356701145942621_5572971298026958959_n.mp4?_nc_ht=instagram.fric1-2.fna.fbcdn.net&_nc_cat=105&_nc_ohc=5vtoVq3n3d0AX9VTON7&edm=APfKNqwBAAAA&ccb=7-4&oe=6128BBA6&oh=bdcd45226fa49b7d6cb2fbf24bf2ab5b&_nc_sid=74f7ba)

**Comment by hchorey** [comment]
...ok, that's weird, haha; when linked here it is redirecting to https://scontent.cdninstagram.com/.  However, when clicking the bookmarklet directly from instagram, it loads up in the new tab with https://scontent.fric1-2.fna.fbcdn.net/ which doesn't show anything.

**Comment by saschaheim** [comment]
Will try to fix this with a more generic solution.

**Comment by saschaheim** [comment]
Hi 10.0.4 released now.
Please try and let me now if it works for you.

Thanks

**Comment by hchorey** [comment]
Perfect! Works great. :)
