### ISSUE TITLE
Instantgram often grabs avatars/profile pics

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#15]
Hello!
10.0.5 is often opening a user's avatar on the timeline instead of grabbing the contents of a post. It seems sporadic, with no predictability, so it's difficult to offer an example post.

Firefox 94.0.1 (64-bit), United States

**Comment by SportConnects** [comment]
Yes Instagram has unfortunately made design changes again so that it comes back to errors.
As soon as I have more time I can take care of the problem.

Thanks for your message

**Comment by saschaheim** [comment]
Hi sorry for my late response,
in the next few weeks i will provide a new update which will adresses your issue.
So stay tuned.

Thanks Sascha
