### ISSUE TITLE
10.1.0 sometimes grabs the wrong photo

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#16]
Hello! First I want to thank you for dutifully updating this. It's a great tool that I really think you should know people are grateful for, especially me, and I don't really have anywhere other than here to tell you that!

Second I'd like to report that 10.1.0 is occasionally grabbing the wrong photo. [This photoset for example](https://www.instagram.com/p/CZIB12lvPWL/), I can't get the second photo, it just gives me the first one twice instead. This is in Firefox 96.0.2 64-bit on Windows.

**Comment by saschaheim** [comment]
Hello,
on which type did you try to grab the photo?
Feed, modal or direct post

**Comment by saschaheim** [comment]
I cannot reproduce the issue.
Tried it in Firefox 96.0.3 64bit and works flawlessly.
I know from the past that you have had problems before. 
Maybe your browser is the problem?

**Comment by Orudeon** [comment]
Hi, I also can't replicate the issue anymore! That's so weird. I guess they made a code change that your script works with again. I tried it on five posts I had saved that I had had the issue with, and they all worked fine. So I suppose this can be tentatively closed.
