### ISSUE TITLE
Can't save most types of videos anymore.

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#17]
Hello! On 10.1.0, most videos and reels don't download. The 'trying to load' prompt pops up, and nothing else happens. [Example affected video](https://www.instagram.com/p/CaX_q1Vh7Wr/).

Firefox 97.0.1 (64 bit) on Windows 10 64-bit, Northwest United States

**Comment by saschaheim** [comment]
Hello,
will check this asap.

Thanks Sascha

**Comment by Orudeon** [comment]
Stories seem unaffected right now. Thank you!

**Comment by saschaheim** [comment]
Have you tried version 10.1.1 ?

**Comment by Orudeon** [comment]
I had not because I didn't realize there was one (I was looking at releases on the right). However it seems to still happen in 10.1.1, so effectively no change.

**Comment by saschaheim** [comment]
Hi 10.1.2 released now.
Please try and let me now if it works for you.

Thanks

**Comment by Orudeon** [comment]
Thank you for working on this! It seems like it works on reels and stories, but not [normal video posts like this one](https://www.instagram.com/p/CajlJ62oUau/). It is functioning normally / as desired on story videos and story photos.

It also seems to grab photos from normal posts just fine, too.

**Comment by saschaheim** [comment]
I need your help...
Can you record a video of your browser screen and with the console open.
So i can see it?

**Comment by Orudeon** [comment]
Sure, which tab of the console?

**Comment by saschaheim** [comment]
The console tab

**Comment by Orudeon** [comment]
In the last thirty minutes, the script started grabbing some videos, so I had trouble finding one that was still affected. [Here is a video of the console tab](https://www.dropbox.com/s/q7te5dssigvl0st/2022-03-01%2013-46-37.mp4?dl=0), and hopefully it's readable.

**Comment by saschaheim** [comment]
Thanks  i hope the video helps me.
Will work on a new update soon.
