### ISSUE TITLE
10.1.3 and earlier not downloading most photos anymore

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#19]
Many photo posts (timeline and blog view) and **all types** of stories aren't downloadable anymore, throwing errors such as "Did you open any Instagram post? Like for example"
Photos that aren't working: 
https://www.instagram.com/p/CePTuwuLHfY/
https://www.instagram.com/p/CeP5Mabj-IW/

Timeline videos are still working
Windows 10 64-bit, Firefox 101.0 (64-bit)

**Comment by saschaheim** [comment]
Thanks,
yes im already working for a fix.
Stay tuned.

Love Sascha

**Comment by Orudeon** [comment]
Thank you so much! I appreciate everything you do

**Comment by Wag669** [comment]
I just found out that after the latest changes on instagram, the applet is not working, decided to make a post and this guy is already working on a fix.....

**two thumbs up!!!!**

**Comment by saschaheim** [comment]
Hi 11.0.0 released now.
Please try and let me now if it works for you.

Thanks

**Comment by MaestroDaVinci** [comment]
It doesn't work on stories for some reason.

**Comment by saschaheim** [comment]
Bad,
can you tell me your browser name and version you used.

And also please tell me which other parts works or not.

Thanks

**Comment by MaestroDaVinci** [comment]
Chrome Latest version and it works for some reason on firefox, but not on chrome.

**Comment by saschaheim** [comment]
Only stories affected or others too?

**Comment by saschaheim** [comment]
It`s really difficult to help because i have tested on all major browsers with different accounts cleared cache etc. and no issues detected.

**Comment by MaestroDaVinci** [comment]
OK so here it. 
Chrome:
Stories of any kind are not loading not pictures or any videos.  
Videos on a multiple pictures posts don't load. Videos on the timeline loads. 
Videos on a specific post in profile don't. 
Multiple picture posts loads every single picture, but as previously said if there is a video it doesn't load.
Can't seem to find posts with multiple videos to test so that is up to you to test.

**Comment by saschaheim** [comment]
Does it show a dialog box with content failed?

**Comment by saschaheim** [comment]
Under a completely new account it shows me a dialog that it fails.

**Comment by MaestroDaVinci** [comment]
On stories it shows 
Did you open any Instagram post? Like for example
https://www.instagram.com/p/CIGrv1VMBkS/
On videos in multiple picture posts it shows 
Loading
Trying to load
On video on timeline it loads, but the same video from a post it shows
Did you open any Instagram post? Like for example
https://www.instagram.com/p/CIGrv1VMBkS/

**Comment by saschaheim** [comment]
Thanks need some time to find a correct solution for this.
Thanks for your Issue.

PS: Can confirm this BUG

**Comment by Orudeon** [comment]
I can confirm everything appears to work great in Firefox, thank you!

**Comment by saschaheim** [comment]
> I can confirm everything appears to work great in Firefox, thank you!

Ok Great, have you already tried Google Chrome?

**Comment by Orudeon** [comment]
It appears to work on all types of posts, I can't find a complicated post mixed with videos and photos, but stories are all working.
