### ISSUE TITLE
5.0 now skipping posts to prefer videos

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#2]
I can't get Instantgram to open [this photo post by Brock o'Hurn](https://www.instagram.com/p/CFRdgRmnbXI/) when on the timeline because it's... not tall enough I guess? I don't know. A video post is right after it and it's getting preference somehow.

US West Firefox 80.0.1 64-bit on Windows 10

**Comment by saschaheim** [comment]
Can you send me the exact url.
So i can start research on this issue.

Thanks

**Comment by saschaheim** [comment]
It is important that the image is exactly and fit in the viewport, otherwise the image or video will not be recognized.

**Comment by Orudeon** [comment]
That's good to know, so I can shrink the browser window and then it'll get that post I linked

**Comment by saschaheim** [comment]
Closed.
Hope your problem is fixed with my answer.
Thanks.
