### ISSUE TITLE
Nonfunctional on timeline and some profiles

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#20]
Hello! I noticed today that Instantgram lost all functionality other than "did you open an instagram post?" on the timeline. Most posts still work when looking at them individually, so it's not a huge problem.

It also has lost all functionality other than that on some profiles, but I can't figure out why. [Centrfit's profile](https://www.instagram.com/centrfit/) works fine but [one of their trainer's profiles](https://www.instagram.com/bobbydazzler84/) has no functionality. It's really bizarre. Photo posts, reels, and videos still function when looking at them as an individual post rather than carousel view.

Stories remain totally functional.

Firefox 102.0.1 (64 bit), windows 10 64 bit, west coast united states

**Comment by saschaheim** [comment]
Yes, I have noticed that.
I've been working on a solution for a long time.
Instagram changes their backend weekly so it's complicated to provide a fix that works for a while.

Stay tuned hopefully by end of July it is finished.

**Comment by saschaheim** [comment]
Released v12 take a look on this
