### ISSUE TITLE
New malfunction on third image in some posts

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#21]
The new update (12.0) is working great on the timeline. Today I noticed that it was completely nonfunctional [on this post after the second image](https://www.instagram.com/p/ChuwTc9hDQu/). 

[The third image of this post,](https://www.instagram.com/p/ChuvSW4B1Cl/) [this post,](https://www.instagram.com/p/ChutAOlhB1F/) [and this post](https://www.instagram.com/p/ChunnWSJsdK/) are all skipped, going to the next one instead. The third and fifth image of [this post](https://www.instagram.com/p/ChumPtdL95J/) [and also this post](https://www.instagram.com/p/ChukWZQrC2C/) are skipped, going to the next.

I'm still investigating how widespread the issue is.

**Comment by Orudeon** [comment]
It seems like this is becoming more prevalent, it's almost always on posts that have five or more items. It's always the third image skipped, going to the fourth one. [Here's another victim](https://www.instagram.com/p/Ch8KaLVO5Vz/) but they're all over the place.

**Comment by saschaheim** [comment]
Does this concern Firefox or also other browsers?

**Comment by saschaheim** [comment]
On Chrome, my development environment, everything runs fine, including your examples.

**Comment by saschaheim** [comment]
Have now tested Firefox also here everything works fine.
It could be that Instagram has different frontend versions in different countries.

Where do you come from?
If I know where you are coming from, I'll try a VPN to find out what's going on.

**Comment by Orudeon** [comment]
I'm on the West Coast of the United States. I also just tested it in Chrome and it works fine, I don't know why it's not working right in Firefox. That's pretty weird.

**Comment by Orudeon** [comment]
Some stories are now throwing the typical 'did you try an instagram post?' errors in Firefox, but not in Chrome. In Chrome the video just opens in a new tab and lets me right-click save as. I would put this in a new issue, but since it's only happening in Firefox, it might be related to the issue in Firefox where the third image in some posts is being skipped.

**Comment by saschaheim** [comment]
Ok will look into this in a few days...

**Comment by saschaheim** [comment]
I have tested this problem in Firefox and I can confirm it.
It is really strange that it works in Chrome but not in Firefox.
I will probably have to introduce browser mechanisms that this problem is finally eliminated from the world.

Will work on this now...

Thanks for your support [Orudeon](https://github.com/Orudeon)
