### ISSUE TITLE
Bizarre skip of first post on timeline and image ignoring problem

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#22]
Instagram is having a field day messing with the extension apparently; today I noticed that using the bookmarklet on the first post on the timeline opens the fourth post on the timeline instead. Every other post appears to work normally, _so far_. Tried in Firefox and Chrome, both latest revisions, windows 10 x64, bookmark v 12. West coast united states.

A few minutes after initially making this topic, I noticed this happens sporadically on other places on the timeline.

Another problem I noticed, a lot of posts are grabbing incorrect images or skipping them entirely. [This post here](https://www.instagram.com/p/CjAEcqvoaui/) grabs the first one correctly. The second image grabs the first photo. The third and fourth image grabs the video in the fifth frame instead. [This post](https://www.instagram.com/p/Ci6A2_ChlI8/) is a good indication of the typical symptom, where each photo is grabbing the one to the left (making the last photo impossible to grab).

You have your work cut out for you, my friend. Sorry they keep doing this, just know the time you spend toiling on this is appreciated

**Comment by saschaheim** [comment]
Thanks working on it....
In few days i will release a new update which fixes all issues.
Note: I have seen instagram has again changed their selectors.
It is every time a cat and mouse game ^_^

**Comment by saschaheim** [comment]
Hello,
the new version is being released right now.
Have fun ^^
