### ISSUE TITLE
Photo order getting scrambled

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#24]
Another new week, another new Instagram tweak. Posts with lots of photos sometimes have the order switched. [This post here has photos 4 and 5 swapped. Photos 7 and 8 are also swapped.](https://www.instagram.com/p/CkMVe7YB7FI/) I've also noticed a small number of posts with photos that are skipped. [Photo 3 in this post](https://www.instagram.com/p/CkIxThSLEwW/) is skipped and can't be grabbed; photos 4 and 5 are swapped.

It seems to only happen in posts with over four photos.

West coast United states, Firefox 106.0.2, Windows 10 64bit

**Comment by saschaheim** [comment]
Ok will look into this now

**Comment by saschaheim** [comment]
Ok I could confirm it.
But it happens only in modals.
It is important to narrow down the problem, it makes the work easier.

**Comment by saschaheim** [comment]
Fixed
