### ISSUE TITLE
Image order scrambling or skipping images

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#28]
[This post](https://www.instagram.com/p/CnpYhMWMfPO/) contains 6 images, but images 3 and 5 can't be grabbed by Instantgram because they all redirect to image 3.

[Same problem in this post](https://www.instagram.com/p/CnnHuWMB4TC/).

Fate is conspiring against me to find posts with other image counts, but you might have come across some, too.

**Comment by saschaheim** [comment]
With the current version it seems to be working again?
Unfortunately I couldn't find any problems with version 2022.12.10

Please try again and write back to me if you get errors again...

Thanks

**Comment by Orudeon** [comment]
I found another post that's presently bugged.

[This post has a weird download attempt order](https://www.instagram.com/p/CoUpBMwM9oG/).
Image 1: Fine
Image 2: Fine
Image 3: Grabs image 2
Image 4: Grabs image 5
Image 5: Fine
Image 6: Fine

I'm still in the west coast United States.

**Comment by saschaheim** [comment]
Ok right now im developing a new detection system while the current one definitly sucks.

Thanks for your support ^^

**Comment by saschaheim** [comment]
Have you still this problem?

**Comment by Orudeon** [comment]
Yup, it's still happening, Not sure how frequently.

**Comment by saschaheim** [comment]
Can confirm this for modal types.
Work on a fix right now...

**Comment by saschaheim** [comment]
Later comes a new rewrite that puts everything in the shade and raises this software to a new level!

Stay tuned...
