### ISSUE TITLE
Sound getting stripped from some videos

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#29]
This is halfway asking if you've noticed this, but either I'm finding a lot of videos that are silent for some reason, or sound is getting stripped from some stories or reels. Unfortunately I haven't found a commonality between videos that are getting their audio stripped.

I'm finding that some stories downloaded by StorySaver or Internet Download Manager seem fine while they're silent if grabbed by Instantgram. It's a bizarre problem that I'm not sure how to dissect. I'm also not sure what to link as any story is going to end up deleted after at most 24 hours.

**Comment by saschaheim** [comment]
Yes i`ve noticed that.

This is not a handy task and needs more time.

Thank you for submitting this issue.

**Comment by saschaheim** [comment]
Found a solution is implemented.
Will soon post a new update.
