### ISSUE TITLE
Some stories open as a square image instead of a tall image.

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#3]
Example: https://www.instagram.com/stories/gamegrumps/2457037091120354610/

Firefox 83.0 (64-bit), Windows 10 64 bit, United States

**Comment by saschaheim** [comment]
Hello Orudeon,
thank you for using this tool.
I have created a fix that should solve your problem. 
Hope it works ^_^

Please give a short feedback if your problem is solved thanks.

**Comment by Orudeon** [comment]
It definitely looks like it's solved the issue, thanks for your expedient work!

**Comment by Orudeon** [comment]
Oh no, I got a URL mismatch on one image with 5.0.1 and it couldn't open it, and now I'm having a tough time figuring out which image it was. I guess just be aware there's a vague issue somewhere but I don't have a testable link at the moment.

**Comment by saschaheim** [comment]
Ok will do a research but this take some time.

**Comment by saschaheim** [comment]
I have reproduced the bug.
It is not an bug directly it cames from instagram itelf.
It is a prevention of saving images.
Will work on this but is not an easy task.

**Comment by saschaheim** [comment]
Hello Orudeon,
your issue should be fixed.
Thanks
