### ISSUE TITLE
Not working anymore for pictures, only working for videos

### ISSUE THREAD

**Issue by Rocket3192** [saschaheim/instantgram#30]
Hello, since Yesterday or maybe the day before the script isn't working at all on pictures anymore, just working for videos, Instagram must have changed something 

Thank you

Console :

```
PostScanner() [instantgram] 2022.12.10 TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at d.execute (<anonymous>:1:4183)
    at x.hostname.x.hostname.i.heading.execute (<anonymous>:1:35659)
    at <anonymous>:1:38835
    at <anonymous>:1:41944
    at <anonymous>:1:41949
```

**Comment by saschaheim** [comment]
Hello thank you for submitting a problem.

In what context is your problem?
Example: Stories, Feed, Profiles

**Comment by Rocket3192** [comment]
Since yesterday it's working again

**Comment by saschaheim** [comment]
Thanks will fix all asap
