### ISSUE TITLE
Reels Fail to download  2023.04.12

### ISSUE THREAD

**Issue by likwidoxigen** [saschaheim/instantgram#31]
2023.04.12 Fails to download reels like [this one](https://www.instagram.com/p/CrEfI-2J-zB/?img_index=1).

`Uncaught (in promise) TypeError: e[0] is undefined
(function(){;(()=>{"use strict";var v;(y=v=v||{}).Image="IMAGE",y.Video="VIDEO",y.UNDEFINED="UNDEFINED";class l{getName(){return"FeedScanner"}async execute(d,s){let c=!1;try{let e,t,o,a,n=null,i=v.UNDEFINED,r=!1,l="._aagv";if(null==n){a=document.getElementsByTagName("article");let n=[];for(let o=0;o<a.length;o++){let e,t=null!==a[o].querySelector("._9zm0")||null!==a[o].querySelector("._9zm2");var m;e=t:1:38554
`

**Comment by saschaheim** [comment]
Thanks for submitting this issue.
Working on a fix...

**Comment by likwidoxigen** [comment]
Thank you!
