### ISSUE TITLE
Most posts not recognized anymore unless navigating on profile

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#32]
First of all, the timeline and stories still seem to work fine.

However, when you open an instagram post in a new tab or from a link or something like that, almost universally Instantgram can't recognize it. If you click into a post from a profile, it usually works. Reels seem to fail to process at all.

[Here's an example post.](https://www.instagram.com/p/Crnz0CQLIrl/) Works on the timeline, works when browsing a profile, doesn't work otherwise.

[This reel works.](https://www.instagram.com/p/CrhA0grhjp_/) [This reel](https://www.instagram.com/p/Cq3yRyvNo-f/) never even gives an error.

Firefox 112.0.2, Windows 10, USA west coast.

**Comment by saschaheim** [comment]
Thank you for reporting the issue.
I have developed a completely new bookmarklet, and I am currently preparing for its release.

**Comment by saschaheim** [comment]
With the new bookmarklet no more problems will arise unless instagram changes something fundamental in the backend

**Comment by saschaheim** [comment]
So far, it has always been a cat-and-mouse game which was really annoying, and that has now prompted me to pull the plug and start completely from scratch with a new approach.
