### ISSUE TITLE
Instantgram Light

### ISSUE THREAD

**Issue by saschaheim** [saschaheim/instantgram#33]
Hello Supporters,

I have to tell you that unfortunately I have to stop the support for Firefox in the full [instantgram] version.
This step had to be done because Firefox does not support bookmarks in the bookmarks bar that are more than 65 kilobytes long.
I am infinitely sorry, there is also a bugtrack on firefox for this problem and I hope one day this will be fixed.

But I have created a slimmed down version that works with Firefox. The difference between the light and the full version is that in the light variant no modal popups are displayed.

The light version will also not get any new features but only hot fixes.

Who wants a further development should use [instantgram] here the latest features are implemented.

The light version is available here:
[https://github.com/ThinkBIG-Company/instantgram-light](https://github.com/ThinkBIG-Company/instantgram-light)

Thanks a lot
Sascha

**Comment by Orudeon** [comment]
Oh, that's unfortunate. Is Firefox proving difficult to develop for? I noticed I can't drag the full version onto my bookmarks bar and editing it into other bookmarks wasnt working.

**Comment by saschaheim** [comment]
That's why the light version was created because firefox does not allow more than 65 kilobytes as a bookmarklet.

Thank you my friend for using my software for so long.

**Comment by Orudeon** [comment]
Thank you for diligently maintaining it! I'm merely a user of it, you are the one doing all the hard work. I am so appreciative that you make this tool for people all over the world to use.
