### ISSUE TITLE
Can't Bookmark on Firefox 

### ISSUE THREAD

**Issue by MaestroDaVinci** [saschaheim/instantgram#34]
Hello so i just noticed that there is a new version so i tried to update it, but for some reason it didn't work. I'm on the latest version of Firefox and only here it doesn't work. I tried adding it with and without addons, but both ways it didn't work.

**Comment by saschaheim** [comment]
Please read this topic about this!
https://github.com/ThinkBIG-Company/instantgram/issues/33
