### ISSUE TITLE
Can't open the website in Firefox

### ISSUE THREAD

**Issue by onmyouji** [saschaheim/instantgram#37]
Hello,

When I tried to open the websites (both https://thinkbig-company.github.io/instantgram-light/ and https://thinkbig-company.github.io/instantgram/) in Firefox, the page keeps refreshing repeatedly by itself. It's like it keeps reloading over and over.

Anyone having the same issue?

I'm on Windows 10 Home 64-bit Version 22H2 (OS Build 19045.4412)
Firefox 126.0.1

**Comment by saschaheim** [comment]
Which language do you use in your browser?

**Comment by onmyouji** [comment]
English

![2024-06-11_163951](https://github.com/ThinkBIG-Company/instantgram/assets/8424198/231fde17-adc5-490f-836a-a852b9336e82)


![2024-06-11_164034](https://github.com/ThinkBIG-Company/instantgram/assets/8424198/79fba476-c798-4eba-a0d8-3f8588441169)


Screen capture:


https://github.com/ThinkBIG-Company/instantgram/assets/8424198/908d12a8-278e-412b-b70e-c843db280e51

**Comment by saschaheim** [comment]
Ok found the issue thanks for reporting

**Comment by saschaheim** [comment]
Should be fixed please try again
Thanks for submitting your issue...
