### ISSUE TITLE
Videos no longer downloadable

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#4]
As of some time in the last two hours, posted videos can't be downloaded with 5.0.2 (Firefox 83 64-bit, windows 10, west coast united states). It seems like it affects other Instagram extensions—I have another extension that adds volume control, as a side effect it adds right-clicking to save videos, but this no longer works with it.

Story videos seem unaffected by this change, but that might not be forever.

**Comment by saschaheim** [comment]
Can confirm the bug.
Will post fix soon.
Thanks

**Comment by Orudeon** [comment]
I noticed that opening the video in a Private Browsing tab alleviates the issue and allows all of my instagram-related extensions and video downloading softwares to access them normally, which is bizarre. My guess? It's related to Facebook Container, which doesn't run in Private mode.

**Comment by saschaheim** [comment]
I cannot fix this issue.
Have tested on my own instagram account and detected that some videos have a new leeching protection.
Instagram want to protect their videos from steeling or something else.
This technology is called blob: videos.
I could not find any solution that adress this problem sorry.

**Comment by saschaheim** [comment]
The only way to download these videos are openening the browser developer console an search in the "network" tab the stream e.g mp4 video file.
For normal people this is horrible and definitely not a solution.

**Comment by Orudeon** [comment]
Wow, thanks Instagram. That really sucks. Thanks for looking into it, you did what you could.

I also submitted a bug to Firefox's facebook container development page, since it seems to be what's causing the issue as Chrome seems unaffected, unless you're getting the problem everywhere?

**Comment by mads2** [comment]
> The only way to download these videos are openening the browser developer console an search in the "network" tab the stream e.g mp4 video file.
> For normal people this is horrible and definitely not a solution.

I can't find the video stream in the developer console. 
Opening in a private window works fine in Chrome though only for public profiles.

**Comment by saschaheim** [comment]
Instagram's anti-copying measures have improved again and it has become even more difficult or almost impossible to download some videos.
In this regard, I will stop my efforts for now. 
It's already driving me crazy.
Sorry that i can not say anything else.

**Comment by Orudeon** [comment]
I'm still pretty sure something about Firefox's facebook container extension is breaking things like instantgram and video controls for instagram. Instantgram 5.0.2 still downloads videos just fine for me in chrome at all times, and in firefox private windows.

**Comment by saschaheim** [comment]
Hello version 6 is on the way with blob video support and many other improvements.
Also, the update checker is coming back. 
So stay tuned.
Love Sascha

**Comment by saschaheim** [comment]
Hello all,
version 6 is available 😊
Please test diligently and report any error or even if it works for you 🙏

**Comment by Orudeon** [comment]
Video downloads work! Thanks so much. This is a nice overlay, too
