### ISSUE TITLE
bookmarklet not getting the highest resolution image in instagram stories 

### ISSUE THREAD

**Issue by Wag669** [saschaheim/instantgram#5]
I'd like to report an issue

As the title says, I discovered today that the bookmarklet doesn't get the best resolution available in instagram stories, instead, it goes for the 1080p version

Example:

Let's go to https://www.instagram.com/sinn_spezialuhren and go through the first _highlight_ called **Technology**
And run the bookmarklet on the last story (picture) posted, which at this time is one day old

When I run the bookmarklet I get a 750X1333p version of this image

`https://instagram.fath5-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/p750x750/180434214_212459933683363_1306407181531314571_n.jpg?tp=1&_nc_ht=instagram.fath5-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=QPIANPadM-cAX_Y20Mf&edm=ANmP7GQBAAAA&ccb=7-4&oh=f845105c0ecd7a7e9a26d598372b413e&oe=609247E3&_nc_sid=276363&ig_cache_key=MjU2NDU1MTM0ODg5NDYxMDk3OA%3D%3D.2-ccb7-4`

If I go through the page source I can find a 1125x2000p version of the same image 

`https://instagram.fath5-1.fna.fbcdn.net/v/t51.2885-15/e35/180434214_212459933683363_1306407181531314571_n.jpg?tp=1&_nc_ht=instagram.fath5-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=QPIANPadM-cAX_Y20Mf&edm=ANmP7GQBAAAA&ccb=7-4&oh=5a77b14fe3ab6cae58d99d55d8e831b0&oe=6092A14D&_nc_sid=276363&ig_cache_key=MjU2NDU1MTM0ODg5NDYxMDk3OA%3D%3D.2-ccb7-4
`

**Comment by saschaheim** [comment]
Will check and fix asap.

**Comment by saschaheim** [comment]
It is now ready.
Very rarely it throw an error because of using new browser technologies.
Will look into that and post a fix for that.

**Comment by Wag669** [comment]
> 
> 
> It is now ready.
> Very rarely it throw an error because of using new browser technologies.
> Will look into that and post a fix for that.

Wow.... That was quick!

So I was digging around and found that half the times the full-ress image throws an error (cropped image) and came here to post it, but I see you are way ahead of me!

Thanx again for the great work!!!

**Comment by saschaheim** [comment]
Hello have forgotten to update other modules as well.
Have removed the release to fix this issues.
Will re-release soon.

**Comment by saschaheim** [comment]
Hopefully Fixed ^_^

**Comment by Wag669** [comment]
> 
> 
> Hopefully Fixed ^_^

so far so good :)
