### ISSUE TITLE
7.1.2 opens two tabs of the image from posts

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#7]
Hello! 
When looking at a post such as [this artwork piece](https://www.instagram.com/p/CNaNR60HF02/), 7.1.2's bookmarklet opens the image twice. The tabs/URLs seem identical as my dupe tab closer reports them as duplicates.

This doesn't happen on the timeline/front page or in the post viewing carousel from the person's instagram page.

**Comment by saschaheim** [comment]
Ok which browser did you use and which version?
Then is this an instagram post or a direct one so like the url you wrote?

Thanks

**Comment by saschaheim** [comment]
Ok I was able to reproduce this error in Firefox.
Working on a fix
Thanks

**Comment by saschaheim** [comment]
Have it fixed will be released soon.
