### ISSUE TITLE
Another type error when downloading video

### ISSUE THREAD

**Issue by ale-carra** [saschaheim/instantgram#8]
After fixing #6 a different error appears when attempting to download a feed video with the same user that had that issue and with version 8.0.0. Feed photos and stories work fine

Uncaught TypeError: e[Object.keys(...).find(...)] is undefined
(function(){;!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule:1:35257

**Comment by saschaheim** [comment]
Ok need to make the video downloader more robustly.

**Comment by saschaheim** [comment]
I hope with the latest release the error is gone.
But i need to say sometimes videos cannot be downloaded because instagram has made some changes in their backend to prevent leeching.
Let me know if this issue still exists.

Thanks
