### ISSUE TITLE
After updating to 8.0.0 "update" to 7.1.2 is suggested

### ISSUE THREAD

**Issue by ale-carra** [saschaheim/instantgram#9]
This appears on the console after updating to version 8.0.0

[instantgram] Installed version: 8.0.0 | New update: 7.1.2

**Comment by saschaheim** [comment]
Oh have forgotten to publish release informations for updater as well.
Thanks for your issue 👍 

Will fix that soon 👌

**Comment by saschaheim** [comment]
Released 8.0.2 which adressed your issue.
